/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author deng_875452
 */
public class BlockOverride extends javax.swing.JPanel {

    /**
     * Creates new form BlockOverride
     */
    public BlockOverride() {
        initComponents();
        String text = "";
        for (int i = 0; i < 256; i++) {
            if (Math.random() >= .5)
                text += (char) (Math.random() * 26 + 97);
            else
                text += (char) (Math.random() * 26 + 65);
            if (i % 48 == 47)
                text += "\n";
        }
        textArea_text.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Text = new javax.swing.JLabel();
        label_Type = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_type = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea_text = new javax.swing.JTextArea();

        label_Text.setText("Type the text below without making a mistake to disable DoHomework");

        label_Type.setText("Type it here");

        textArea_type.setColumns(20);
        textArea_type.setRows(5);
        textArea_type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textArea_typeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textArea_typeKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textArea_type);

        textArea_text.setColumns(20);
        textArea_text.setRows(5);
        jScrollPane2.setViewportView(textArea_text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_Type)
                    .addComponent(label_Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_Text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(label_Type)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textArea_typeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textArea_typeKeyTyped
        int currLength = textArea_type.getText().length();
        if (!textArea_type.getText().equals(textArea_text.getText().substring(0, currLength))) {
            textArea_type.setText("");
        }
    }//GEN-LAST:event_textArea_typeKeyTyped

    private void textArea_typeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textArea_typeKeyPressed
        int currLength = textArea_type.getText().length();
        if (!textArea_type.getText().equals(textArea_text.getText().substring(0, currLength))) {
            textArea_type.setText("");
        }
    }//GEN-LAST:event_textArea_typeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_Text;
    private javax.swing.JLabel label_Type;
    private javax.swing.JTextArea textArea_text;
    private javax.swing.JTextArea textArea_type;
    // End of variables declaration//GEN-END:variables

    public String getText() {
        return textArea_text.getText();
    }
    
    public String getType() {
        return textArea_type.getText();
    }
    
}
